version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y jq

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id docker-user --query SecretString --output text)
        DOCKER_USERNAME=$(echo $SECRET_JSON | jq -r '.username')
        DOCKER_PASSWORD=$(echo $SECRET_JSON | jq -r '.password')

        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - echo Retrieving credentials from Secrets Manager
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id ecw/server/env --query SecretString --output text)
        export DB_USER=$(echo $SECRET_JSON | jq -r '.DB_USER')
        export DB_PASSWORD=$(echo $SECRET_JSON | jq -r '.DB_PASSWORD')
        export DB_HOST=$(echo $SECRET_JSON | jq -r '.DB_HOST')
        export DB_PORT=$(echo $SECRET_JSON | jq -r '.DB_PORT')
        export DB_NAME=$(echo $SECRET_JSON | jq -r '.DB_NAME')
        export JWT_SECRET_KEY=$(echo $SECRET_JSON | jq -r '.JWT_SECRET_KEY')

  build:
    commands:
      - echo Building Docker images...
      - docker build --build-arg DB_USER=$DB_USER --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_HOST=$DB_HOST --build-arg DB_PORT=$DB_PORT --build-arg DB_NAME=$DB_NAME --build-arg JWT_SECRET_KEY=$JWT_SECRET_KEY -t quyld17/ecw-server:latest .

  post_build:
    commands:
      - echo Pushing Docker images to Docker Hub...
      - docker push quyld17/ecw-server:latest
